### ISSUE TITLE
Can't build on ESP-IDF

### ISSUE THREAD

**Issue by formatBCE** [hugobloem/esp-ha-speech#3]
Looks like esp32s3 is incompatible with both 5.0 and 4.4.4 ESP-IDF releases.

**Comment by formatBCE** [comment]
Looks like esp32s3 is incompatible with both 5.0 and 4.4.4 ESP-IDF releases.

**Comment by christian-nils** [comment]
I could build it with ESP-IDF v5.0. See chip compatibility: https://github.com/espressif/esp-idf#esp-idf-release-and-soc-compatibility

**Comment by formatBCE** [comment]
I have same stated error, when trying to build :(

**Comment by christian-nils** [comment]
Which error are you referring to? I had issues to build the firmware as others https://github.com/hugobloem/esp-ha-speech/issues/2 and https://github.com/hugobloem/esp-ha-speech/issues/1 . But applying the mentioned fixes in each issues, I could build with v5.0.

**Comment by formatBCE** [comment]
OMG sorry I wasn't paying attention to thread I'm writing to.

Yeah, I'm referring to #2, and I didn't see this exact solution. Will try, thanks for help.

**Comment by christian-nils** [comment]
Alright, no worries! :smiley:

**Comment by formatBCE** [comment]
Yes, with following #1 and #2 it seems to boot normally. Some reboots here and there, but not continuous.

**Comment by hugobloem** [comment]
Sorry, I haven't been able to find time to work on this. I have merged your pr. 

Thank you!
