### ISSUE TITLE
Audio response doesn't work

### ISSUE THREAD

**Issue by formatBCE** [hugobloem/esp-ha-speech#5]
On illustrational video device responds back with sound. I don't hear any sounds from mine. Is there some setup, turned off my default, or is my device somehow defective?

**Comment by christian-nils** [comment]
Could you play music via the Media Player with the original firmware? If yes, then your device should not be defective.

**Comment by hugobloem** [comment]
Hi, the sounds should work by default. I didn't program that bit as it was implemented by default in [esp-box](https://github.com/espressif/esp-box). You could try to flash that factory demo and see if that works?

**Comment by formatBCE** [comment]
I didn't hear any sounds on factory firmware either. I guess it's device's fault...

**Comment by hugobloem** [comment]
Sorry to hear that. I hope you can exchange it.
