### ISSUE TITLE
Implementation of Hermes MQTT protocol

### ISSUE THREAD

**Issue by christian-nils** [hugobloem/esp-ha-speech#9]
Hi @hugobloem,

I remember you mentioned you wanted to integrate esp-ha-speech with Rhasspy in a way that it could leverage Rhasspy's Speech to Text capability (https://www.reddit.com/r/homeassistant/comments/11y9a88/comment/jd6uggg/?utm_source=share&utm_medium=web2x&context=3).
Is it still something you plan to do? How can I help? I am far from being a C developer, but happy to contribute.

Thanks,

CN

**Comment by hugobloem** [comment]
Hi,

This is actually my first C project as well and I am learning as I go. I am planning on implementing responses from rhasspy (/future Home Assistant versions).

I just need to make myself a list of what things are the priority at the moment. The code as of now works, but it does need to become easier to start with. Next to that there are quite a few features that other people mentioned on Reddit that I think would help this project. The question is what to work on first...

If you want to give it a go yourself you're more than welcome to. You can open a PR to submit any changes.

**Comment by christian-nils** [comment]
Thanks for your detailed reply! :) I will have a look at implementing the communication to Rhasspy to use the esp-box as a satellite. I saw this [repo](https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/) that implements the protocol so that may help out. I'll keep you updated if I can get something working!

**Comment by christian-nils** [comment]
@hugobloem : Just as a heads-up, I have started to implement it (https://github.com/christian-nils/esp-ha-speech/tree/feat-rhasspy-mqtt-satellite). I can use Rhasspy for the ASR now and it did work to turn on/off some entities in Home Assistant. The whole process is not yet well integrated, there are plenty of bugs surely, but I think it is still a step forward.

**Comment by hugobloem** [comment]
Amazing! I am excited to try this out. 

This weekend is going to be cold and rainy so I will finally have time to get back to this.
